import { mount, flushPromises } from '@vue/test-utils'
import { afterEach, describe, expect, it, vi } from 'vitest'
import axe from 'axe-core'
import SelectInput from './SelectInput.vue'
import SearchSelectInput from './SearchSelectInput.vue'
import FormField from './FormField.vue'
import { h } from 'vue'

const options = [{ value: 'admin', label: 'Admin' }, { value: 'member', label: 'Member' }, { value: 'blocked', label: 'Blocked', disabled: true }]
const wrappers = []
afterEach(() => { wrappers.forEach(wrapper => wrapper.unmount()); wrappers.length = 0; vi.useRealTimers() })
function create(props = {}) {
  const wrapper = mount(SelectInput, { attachTo: document.body, props: { options, ...props, 'onUpdate:modelValue': value => wrapper.setProps({ modelValue: value }) }, attrs: { 'aria-label': 'Role' } })
  wrappers.push(wrapper)
  return wrapper
}
describe('Searchable SelectInput', () => {
  it('filters locally, selects by keyboard, and preserves typed values', async () => {
    const wrapper = create({ modelValue: 'admin' })
    await wrapper.find('button').trigger('click')
    const input = wrapper.find('[role="combobox"]')
    expect(document.activeElement).toBe(input.element)
    await input.setValue('MEM')
    expect(wrapper.findAll('[role="option"]')).toHaveLength(1)
    await input.trigger('keydown', { key: 'ArrowDown' })
    await input.trigger('keydown', { key: 'Enter' })
    expect(wrapper.props('modelValue')).toBe('member')
    expect(wrapper.emitted('change')[0][0].target.value).toBe('member')
    expect(document.activeElement).toBe(wrapper.find('button').element)
    const numeric = create({ options: [{ value: 5, label: 'Five' }], modelValue: 10 })
    await numeric.find('button').trigger('click')
    await numeric.find('[role="option"]').trigger('mousedown')
    expect(numeric.props('modelValue')).toBe(5)
  })
  it('skips disabled options, supports Escape/Tab/outside close and empty results', async () => {
    const wrapper = create()
    await wrapper.find('button').trigger('keydown', { key: 'ArrowDown' })
    const input = wrapper.find('input')
    await input.trigger('keydown', { key: 'ArrowUp' })
    expect(input.attributes('aria-activedescendant')).toMatch(/-1$/)
    await wrapper.findAll('[role="option"]')[2].trigger('mousedown')
    expect(wrapper.emitted('update:modelValue')).toBeUndefined()
    await input.setValue('unknown')
    expect(wrapper.find('[role="status"]').text()).toBeTruthy()
    await input.trigger('keydown', { key: 'Enter' })
    await input.trigger('keydown', { key: 'Escape' })
    expect(wrapper.find('[role="listbox"]').exists()).toBe(false)
    await wrapper.find('button').trigger('click')
    await wrapper.find('input').trigger('keydown', { key: 'Tab' })
    expect(wrapper.find('input').exists()).toBe(false)
    await wrapper.find('button').trigger('click')
    document.body.dispatchEvent(new Event('pointerdown', { bubbles: true }))
    await flushPromises()
    expect(wrapper.find('input').exists()).toBe(false)
    await wrapper.setProps({ disabled: true })
    await wrapper.find('button').trigger('click')
    expect(wrapper.find('input').exists()).toBe(false)
  })
  it('debounces bounded remote queries and rejects stale responses', async () => {
    vi.useFakeTimers()
    const pending = []
    const loader = vi.fn(args => new Promise(resolve => pending.push({ args, resolve })))
    const wrapper = create({ loadOptions: loader, limit: 999 })
    await wrapper.find('button').trigger('click')
    await vi.advanceTimersByTimeAsync(400)
    expect(loader).not.toHaveBeenCalled()
    await wrapper.find('input').setValue('ad')
    await vi.advanceTimersByTimeAsync(299)
    expect(loader).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(pending[0].args.limit).toBe(50)
    expect(wrapper.find('[role="status"]').exists()).toBe(true)
    await wrapper.find('input').setValue('mem')
    expect(pending[0].args.signal.aborted).toBe(true)
    await vi.advanceTimersByTimeAsync(300)
    pending[1].resolve([options[1]])
    await flushPromises()
    pending[0].resolve([options[0]])
    await flushPromises()
    expect(wrapper.find('[role="option"]').text()).toBe('Member')
    await wrapper.find('[role="option"]').trigger('mousedown')
    expect(wrapper.find('button').text()).toBe('Member')
  })
  it('offers retry after remote failure and cancels when disabled or unmounted', async () => {
    vi.useFakeTimers()
    const loader = vi.fn().mockRejectedValueOnce(new Error('Unavailable')).mockResolvedValueOnce(options)
    const wrapper = create({ loadOptions: loader })
    await wrapper.find('button').trigger('click')
    await wrapper.find('input').setValue('admin')
    await vi.advanceTimersByTimeAsync(300)
    await flushPromises()
    expect(wrapper.findAll('button')).toHaveLength(2)
    await wrapper.findAll('button')[1].trigger('click')
    await vi.advanceTimersByTimeAsync(300)
    await flushPromises()
    expect(wrapper.findAll('[role="option"]')).toHaveLength(3)
    await wrapper.setProps({ disabled: true })
    expect(wrapper.find('input').exists()).toBe(false)
    wrapper.unmount()
  })
  it('exposes labels/errors and passes axe with the list open', async () => {
    const wrapper = mount(FormField, { attachTo: document.body, props: { label: 'Role', error: 'Invalid role' }, slots: { default: () => h(SearchSelectInput, { options, modelValue: 'admin' }) } })
    wrappers.push(wrapper)
    const trigger = wrapper.find('button')
    expect(wrapper.find('label').attributes('for')).toBe(trigger.attributes('id'))
    expect(trigger.attributes('aria-invalid')).toBe('true')
    expect(trigger.attributes('aria-describedby')).toContain('error')
    await trigger.trigger('click')
    expect((await axe.run(wrapper.element, { rules: { 'color-contrast': { enabled: false } } })).violations).toEqual([])
  })
})
