import { ref } from 'vue'
import { finishNavigationLoading, startNavigationLoading } from './navigationLoading'

const messages = {
  id: {
    'security.additional_verification': 'Verifikasi keamanan tambahan', 'security.step_up_hint': 'Konfirmasi identitas Anda sebelum melanjutkan tindakan sensitif ini.', 'security.totp_or_email_hint': 'Gunakan kode aplikasi autentikator atau kode yang dikirim melalui email.', 'security.totp_title': 'Aplikasi autentikator', 'security.totp_hint': 'Gunakan kode TOTP meskipun email sedang tidak dapat diakses.', 'security.totp_setup_hint': 'Tambahkan secret berikut ke aplikasi autentikator, lalu masukkan kode 6 digit.', 'security.totp_enabled': 'Aplikasi autentikator berhasil diaktifkan.', 'security.totp_disabled': 'Aplikasi autentikator berhasil dinonaktifkan.', 'security.email_revert_title': 'Batalkan perubahan email', 'security.email_revert_hint': 'Kami sedang memulihkan alamat email lama dan mengakhiri seluruh sesi.', 'security.email_reverted': 'Alamat email berhasil dipulihkan. Silakan login kembali.',
    'nav.account_security': 'Keamanan akun',
    'security.title': 'Keamanan akun', 'security.subtitle': 'Kelola kredensial dan tinjau aktivitas login akun Anda.', 'security.current_password': 'Kata sandi saat ini', 'security.change_password': 'Ganti kata sandi', 'security.changing_password': 'Mengganti…', 'security.password_changed': 'Kata sandi berhasil diubah dan sesi lain telah diakhiri.', 'security.change_email': 'Ganti email', 'security.new_email': 'Email baru', 'security.send_email_code': 'Kirim kode verifikasi', 'security.sending_code': 'Mengirim kode…', 'security.email_code_sent': 'Kode verifikasi telah dikirim ke {email}.', 'security.verify_email': 'Verifikasi email baru', 'security.email_changed': 'Email berhasil diubah.', 'security.login_history': 'Riwayat login', 'security.event': 'Aktivitas', 'security.time': 'Waktu', 'security.empty_history': 'Belum ada riwayat keamanan.', 'security.recovery_title': 'Recovery code', 'security.recovery_hint': 'Konfirmasi kata sandi dan OTP sebelum membuat ulang recovery code.', 'security.request_recovery': 'Kirim OTP', 'security.regenerate': 'Buat ulang kode', 'security.recovery_generated': 'Recovery code baru berhasil dibuat.', 'security.recovery_once': 'Simpan sekarang. Kode hanya ditampilkan sekali.', 'security.passkeys': 'Passkey', 'security.passkey_hint': 'Gunakan biometrik atau kunci keamanan pada browser yang mendukung.', 'security.passkey_name': 'Nama perangkat', 'security.add_passkey': 'Tambah passkey', 'security.adding_passkey': 'Menambahkan…', 'security.passkey_added': 'Passkey berhasil ditambahkan.', 'security.passkey_removed': 'Passkey berhasil dihapus.', 'security.remove_passkey': 'Hapus passkey {name}', 'security.confirm_remove_passkey': 'Passkey {name} akan dihapus.', 'security.passkeys_disabled': 'Passkey belum dikonfigurasi pada server.', 'security.passkeys_unsupported': 'Browser ini belum mendukung passkey modern.', 'security.never_used': 'Belum pernah digunakan', 'security.use_passkey': 'Masuk dengan passkey', 'security.using_passkey': 'Memverifikasi passkey…',
    'permission.account_security.view.name': 'Lihat keamanan akun', 'permission.account_security.view.description': 'Melihat pengaturan keamanan dan riwayat login milik sendiri.', 'permission.account_security.update.name': 'Ubah keamanan akun', 'permission.account_security.update.description': 'Mengubah password, email, recovery code, dan passkey milik sendiri.',
    'profile.title': 'Profil', 'profile.subtitle': 'Kelola informasi pribadi dan akses keamanan akun Anda.', 'profile.menu': 'Profil', 'profile.avatar_alt': 'Foto profil', 'profile.account_info': 'Informasi akun', 'profile.member_since': 'Bergabung sejak', 'profile.verified': 'Email terverifikasi', 'profile.unverified': 'Email belum terverifikasi', 'profile.security_link_hint': 'Password, email, recovery code, dan passkey.', 'profile.sessions_link_hint': 'Tinjau perangkat dan sesi login aktif.', 'profile.avatar_title': 'Foto profil', 'profile.avatar_hint': 'JPEG, PNG, atau WebP hingga 5 MB.', 'profile.avatar_file': 'Pilih gambar', 'profile.upload': 'Unggah', 'profile.uploading': 'Mengunggah…', 'profile.remove': 'Hapus foto', 'profile.avatar_updated': 'Foto profil berhasil diperbarui.', 'profile.avatar_removed': 'Foto profil berhasil dihapus.',
    'permission.profile.view.name': 'Lihat profil', 'permission.profile.view.description': 'Melihat profil akun sendiri.', 'permission.profile.update.name': 'Ubah profil', 'permission.profile.update.description': 'Mengubah foto dan informasi profil akun sendiri.',
    'profile.sections': 'Bagian profil', 'profile.account_menu': 'Menu akun', 'profile.tab_overview': 'Ringkasan', 'profile.tab_security': 'Keamanan akun', 'profile.tab_devices': 'Perangkat aktif',
    'profile.personal_information': 'Informasi pribadi', 'profile.personal_hint': 'Perbarui nama dan nomor telepon yang terhubung ke akun Anda.', 'profile.edit_personal': 'Edit informasi pribadi', 'profile.first_name': 'Nama depan', 'profile.last_name': 'Nama belakang', 'profile.phone': 'Nomor telepon', 'profile.personal_updated': 'Informasi pribadi berhasil diperbarui.', 'profile.change_photo': 'Ganti foto profil', 'profile.avatar_conversion_hint': 'Semua foto dikonversi ke AVIF maksimal 50 KB.', 'profile.password_hint': 'Perbarui kata sandi akun secara aman.', 'profile.email_hint': 'Ganti email dengan verifikasi ulang.', 'profile.history_hint': 'Tinjau aktivitas keamanan dan login terbaru.',
    'auth.otp_or_recovery': 'Masukkan OTP 6 digit atau recovery code 10 karakter.', 'auth.captcha_hint': 'Selesaikan pemeriksaan keamanan untuk melanjutkan login.', 'auth.session_expired': 'Sesi Anda telah berakhir. Silakan login kembali.',
    'sessions.recovery_title': 'Recovery code', 'sessions.recovery_hint': 'Buat kode sekali pakai untuk masuk saat email OTP tidak dapat diakses.', 'sessions.recovery_generate': 'Buat kode baru', 'sessions.recovery_generating': 'Membuat…', 'sessions.recovery_generated': 'Recovery code baru berhasil dibuat.', 'sessions.recovery_once': 'Simpan sekarang. Kode ini hanya ditampilkan sekali dan setiap kode hanya dapat digunakan satu kali.',
    'admin.open_menu': 'Buka menu',
    'admin.notifications': 'Notifikasi', 'admin.no_notifications': 'Belum ada notifikasi baru.',
    'validation.email_same': 'Email baru harus berbeda dari email saat ini.',
    'validation.required': 'Field ini wajib diisi.', 'validation.too_long': 'Nilai terlalu panjang.', 'validation.email': 'Masukkan alamat email yang valid.', 'validation.password_min': 'Password minimal 12 karakter.', 'validation.password_mismatch': 'Konfirmasi password tidak sama.', 'validation.password_same': 'Password baru harus berbeda dari password saat ini.', 'validation.otp': 'Masukkan kode OTP 6 digit yang valid.', 'validation.otp_or_recovery': 'Masukkan OTP 6 digit atau recovery code 10 karakter.', 'validation.phone': 'Gunakan hanya angka, spasi, +, tanda kurung, titik, atau tanda hubung.', 'validation.role_key': 'Key hanya boleh berisi huruf kecil, angka, dan underscore.', 'validation.fix_fields': 'Periksa kembali field yang ditandai.',
    'nav.home': 'Beranda', 'nav.admin': 'Admin', 'nav.language': 'Bahasa',
    'nav.dashboard': 'Dasbor', 'nav.user_management': 'Manajemen Pengguna', 'nav.users': 'Pengguna', 'nav.roles': 'Role', 'nav.sessions': 'Perangkat aktif', 'nav.audit_logs': 'Log audit', 'nav.jobs': 'Antrean job', 'nav.api_docs': 'Dokumentasi API', 'nav.security_approvals': 'Persetujuan keamanan',
    'common.close': 'Tutup', 'common.done': 'Selesai', 'common.continue': 'Lanjutkan', 'common.verify': 'Verifikasi',
    'common.edit': 'Edit', 'common.view': 'Lihat', 'common.cancel': 'Batal',
    'common.loading_data': 'Memuat data…',
    'api.non_json_response': 'Server mengembalikan respons non-JSON (HTTP {status}).',
    'table.show': 'Tampilkan', 'table.entries': 'baris', 'table.search': 'Cari…', 'table.empty': 'Tidak ada data.', 'table.loading': 'Memuat data…', 'table.showing': 'Menampilkan {from}–{to} dari {total} data', 'table.previous': 'Sebelumnya', 'table.next': 'Berikutnya',
    'common.loading_page': 'Memuat halaman…', 'common.processing': 'Memproses…', 'common.back': 'Kembali', 'common.retry': 'Coba lagi', 'common.back_home': 'Kembali ke beranda', 'common.just_now': 'Baru saja', 'common.close_notification': 'Tutup notifikasi', 'common.save': 'Simpan', 'common.saving': 'Menyimpan…', 'common.delete': 'Hapus', 'common.deleting': 'Menghapus…', 'common.action': 'Aksi', 'common.status': 'Status', 'common.system': 'Sistem', 'common.view_only': 'Hanya lihat',
    'auth.login_required': 'Silakan login terlebih dahulu untuk mengakses halaman admin.', 'auth.otp_sent': 'Kode OTP telah dikirim ke {email}.', 'auth.unverified': 'Akun belum terverifikasi. Kode verifikasi telah dikirim ke {email}.', 'auth.otp_resent': 'Kode OTP baru telah dikirim ke {email}.', 'auth.no_permission': 'Akun ini tidak memiliki izin untuk mengakses panel admin.', 'auth.password_updated': 'Kata sandi berhasil diperbarui. Silakan login.',
    'auth.admin_access': 'Akses admin', 'auth.login_title': 'Masuk ke Vue Rails', 'auth.verify_title': 'Verifikasi OTP', 'auth.login_hint': 'Gunakan akun administrator Anda.', 'auth.otp_hint': 'Masukkan kode 6 digit yang dikirim ke {email}.', 'auth.email': 'Email', 'auth.password': 'Kata sandi', 'auth.confirm_password': 'Konfirmasi kata sandi', 'auth.new_password': 'Kata sandi baru', 'auth.otp': 'Kode OTP', 'auth.forgot': 'Lupa kata sandi?', 'auth.login': 'Login', 'auth.logging_in': 'Masuk…', 'auth.verify': 'Verifikasi', 'auth.verifying': 'Memverifikasi…', 'auth.no_account': 'Belum punya akun?', 'auth.register_member': 'Daftar sebagai member', 'auth.resend': 'Kirim ulang OTP', 'auth.resending': 'Mengirim…', 'auth.resend_countdown': 'Kirim ulang ({seconds}s)', 'auth.password_min': 'Minimal 12 karakter.',
    'toast.success': 'Berhasil', 'toast.error': 'Terjadi kesalahan', 'toast.warning': 'Perhatian', 'toast.info': 'Informasi', 'toast.confirm': 'Konfirmasi tindakan', 'toast.cancel': 'Batal', 'toast.continue': 'Lanjutkan',
    'admin.console': 'Konsol admin', 'admin.menu': 'Menu', 'admin.operational': 'Semua sistem beroperasi', 'admin.collapse_sidebar': 'Kecilkan sidebar', 'admin.expand_sidebar': 'Lebarkan sidebar', 'admin.search': 'Cari atau ketik perintah...', 'admin.administrator': 'Administrator', 'admin.sign_out': 'Keluar', 'admin.signing_out': 'Keluar…',
    'users.title': 'Manajemen pengguna', 'users.subtitle': 'Kelola role dan akses akun.', 'users.search': 'Cari email…', 'users.search_button': 'Cari', 'users.searching': 'Mencari…', 'users.role': 'Role', 'users.verified': 'Terverifikasi', 'users.you': 'Anda', 'users.active': 'Aktif', 'users.inactive': 'Nonaktif', 'users.email_verified': 'Email terverifikasi', 'users.email_unverified': 'Email belum terverifikasi', 'users.empty': 'Pengguna tidak ditemukan.', 'users.updated': '{email} berhasil diperbarui.',
    'users.edit_title': 'Edit pengguna', 'users.edit_user': 'Edit pengguna {email}', 'users.account_status': 'Status akun', 'users.account_status_hint': 'Pengguna nonaktif tidak dapat masuk ke aplikasi.',
    'roles.title': 'Manajemen role', 'roles.subtitle': 'Buat role dan gunakan pada manajemen pengguna.', 'roles.name': 'Nama role', 'roles.key': 'Key', 'roles.description': 'Deskripsi', 'roles.permissions': 'Izin', 'roles.key_help': 'Huruf kecil, angka, dan underscore.', 'roles.add': 'Tambah role', 'roles.adding': 'Menambahkan…', 'roles.created': 'Role baru berhasil dibuat.', 'roles.updated': '{name} berhasil diperbarui.', 'roles.deleted': '{name} berhasil dihapus.', 'roles.confirm_delete': 'Role {name} akan dihapus permanen.', 'roles.users': 'Pengguna', 'roles.empty': 'Belum ada role.',
    'audit.title': 'Log audit', 'audit.subtitle': '100 aktivitas terbaru yang penting bagi keamanan.', 'audit.action': 'Aksi', 'audit.actor': 'Pelaku', 'audit.target': 'Target', 'audit.time': 'Waktu', 'audit.empty': 'Belum ada aktivitas.',
    'sessions.last_seen': 'Aktivitas terakhir', 'sessions.expires_at': 'Kedaluwarsa',
    'sessions.title': 'Perangkat aktif', 'sessions.subtitle': 'Tinjau dan akhiri sesi login pada akun Anda.', 'sessions.device': 'Perangkat / browser', 'sessions.login_time': 'Waktu login', 'sessions.current': 'Saat ini', 'sessions.empty': 'Tidak ada sesi aktif.', 'sessions.unknown_device': 'Perangkat tidak dikenal', 'sessions.revoke': 'Akhiri', 'sessions.revoking': 'Mengakhiri…', 'sessions.revoked': 'Sesi berhasil diakhiri.', 'sessions.revoke_others': 'Akhiri sesi lain', 'sessions.others_revoked': 'Semua sesi lain berhasil diakhiri.', 'sessions.confirm_revoke': 'Sesi pada perangkat ini akan diakhiri.', 'sessions.confirm_revoke_others': 'Semua sesi selain perangkat yang sedang digunakan akan diakhiri.', 'sessions.revoke_device': 'Akhiri sesi {device}', 'sessions.use_sign_out': 'Gunakan tombol Keluar',
    'home.title': 'Stack modern untuk perencanaan perjalanan', 'home.subtitle': 'Vue menangani antarmuka, Rails menyediakan REST API, dan PostgreSQL menyimpan data.', 'home.connecting': 'Menghubungkan ke Rails API…', 'home.connected': 'API terhubung', 'home.disconnected': 'API belum terhubung',
    'dashboard.title': 'Dasbor', 'dashboard.subtitle': 'Ringkasan workspace Vue Rails Anda', 'dashboard.load_failed': 'Dasbor tidak dapat dimuat. Silakan coba kembali.', 'dashboard.total_users': 'Total pengguna', 'dashboard.active_sessions': 'Sesi aktif', 'dashboard.live': 'Langsung', 'dashboard.database': 'Basis data', 'dashboard.connected': 'Terhubung', 'dashboard.authorization': 'Otorisasi', 'dashboard.protected': 'Terlindungi', 'dashboard.overview': 'Ringkasan workspace', 'dashboard.system_activity': 'Aktivitas sistem aplikasi ini', 'dashboard.last_days': '7 hari terakhir', 'dashboard.quick_status': 'Status singkat', 'dashboard.backend_services': 'Layanan backend', 'dashboard.operational': 'Beroperasi', 'dashboard.recent_activity': 'Aktivitas admin terbaru', 'dashboard.auth_events': 'Autentikasi dan kejadian sistem', 'dashboard.event': 'Kejadian', 'dashboard.account': 'Akun', 'dashboard.session_authenticated': 'Sesi admin terautentikasi', 'dashboard.success': 'Berhasil',
    'roles.name_placeholder': 'Contoh: Editor', 'roles.more': 'Lainnya (+{count})', 'roles.permission_modal_title': 'Pilih permission', 'roles.permission_modal_hint': 'Pilih akses halaman dan tindakan yang boleh digunakan role ini.',
    'roles.edit_title': 'Edit role', 'roles.edit_hint': 'Perbarui role dengan key {key}.', 'roles.edit_role': 'Edit role {name}', 'roles.delete_role': 'Hapus role {name}', 'roles.description_placeholder': 'Jelaskan tanggung jawab dan cakupan akses role ini.', 'roles.no_description': 'Belum ada deskripsi.', 'roles.permission_count': '{count} permission',
    'permission.dashboard.view.name': 'Lihat dasbor', 'permission.dashboard.view.description': 'Melihat dasbor admin.',
    'permission.users.view.name': 'Lihat pengguna', 'permission.users.view.description': 'Melihat daftar dan detail pengguna.',
    'permission.users.update.name': 'Ubah pengguna', 'permission.users.update.description': 'Mengubah role dan status pengguna.',
    'permission.roles.view.name': 'Lihat role', 'permission.roles.view.description': 'Melihat daftar role dan permission.',
    'permission.roles.create.name': 'Buat role', 'permission.roles.create.description': 'Membuat role baru dan menetapkan permission awal.',
    'permission.roles.update.name': 'Ubah role', 'permission.roles.update.description': 'Mengubah nama, deskripsi, dan permission role.',
    'permission.roles.delete.name': 'Hapus role', 'permission.roles.delete.description': 'Menghapus role kustom yang tidak digunakan.',
    'permission.audit_logs.view.name': 'Lihat log audit', 'permission.audit_logs.view.description': 'Melihat riwayat aktivitas keamanan.',
    'permission.sessions.view.name': 'Lihat perangkat', 'permission.sessions.view.description': 'Melihat perangkat dan sesi login milik sendiri.', 'permission.sessions.delete.name': 'Hapus sesi', 'permission.sessions.delete.description': 'Mengakhiri sesi login milik sendiri.',
    'permission.jobs.view.name': 'Lihat antrean job', 'permission.jobs.view.description': 'Melihat status antrean dan job gagal.', 'permission.jobs.update.name': 'Kelola job gagal', 'permission.jobs.update.description': 'Mencoba ulang atau menghapus job gagal.', 'permission.api_docs.view.name': 'Lihat dokumentasi API', 'permission.api_docs.view.description': 'Membuka dokumentasi OpenAPI interaktif.',
    'jobs.title': 'Antrean job', 'jobs.subtitle': 'Pantau Solid Queue dan tangani job yang gagal.', 'jobs.ready': 'Siap', 'jobs.scheduled': 'Terjadwal', 'jobs.claimed': 'Diproses', 'jobs.failed': 'Gagal', 'jobs.job': 'Job', 'jobs.error': 'Error', 'jobs.failed_at': 'Waktu gagal', 'jobs.empty': 'Tidak ada job gagal.', 'jobs.retry': 'Coba lagi', 'jobs.discard': 'Hapus', 'jobs.retryed': 'Job dijadwalkan ulang.', 'jobs.discarded': 'Job gagal dihapus.', 'jobs.confirm_retry': 'Job gagal ini akan dicoba ulang.', 'jobs.confirm_discard': 'Job gagal ini akan dihapus permanen.', 'jobs.retry_job': 'Coba ulang job {id}', 'jobs.discard_job': 'Hapus job {id}',
    'api_docs.title': 'Dokumentasi API', 'api_docs.subtitle': 'Kontrak OpenAPI interaktif untuk endpoint Vue Rails.',
    'approvals.title': 'Persetujuan keamanan', 'approvals.subtitle': 'Tinjau perubahan hak akses yang diajukan administrator lain.', 'approvals.action': 'Perubahan', 'approvals.requester': 'Pemohon', 'approvals.requested_at': 'Diajukan', 'approvals.expires_at': 'Kedaluwarsa', 'approvals.review': 'Tinjau dan setujui', 'approvals.approved': 'Perubahan telah disetujui.', 'approvals.empty': 'Tidak ada persetujuan yang menunggu.',
    'permission.security_approvals.view.name': 'Lihat persetujuan keamanan', 'permission.security_approvals.view.description': 'Melihat perubahan admin yang menunggu persetujuan.', 'permission.security_approvals.update.name': 'Setujui perubahan keamanan', 'permission.security_approvals.update.description': 'Menyetujui perubahan sensitif milik administrator lain.',
    'error.403_title': 'Akses ditolak', 'error.403_message': 'Anda tidak memiliki izin untuk membuka halaman ini.', 'error.404_title': 'Halaman tidak ditemukan', 'error.404_message': 'Halaman yang Anda cari tidak tersedia atau telah dipindahkan.', 'error.500_title': 'Terjadi kesalahan', 'error.500_message': 'Aplikasi mengalami masalah yang tidak terduga.',
    'auth.registration': 'Pendaftaran member', 'auth.register_title': 'Buat akun', 'auth.verify_email': 'Verifikasi email', 'auth.register_hint': 'Daftar sebagai member baru.', 'auth.register': 'Daftar', 'auth.registering': 'Mendaftarkan…', 'auth.verify_and_login': 'Verifikasi dan masuk', 'auth.have_account': 'Sudah punya akun?', 'auth.recovery': 'Pemulihan akun', 'auth.forgot_title': 'Lupa kata sandi', 'auth.forgot_hint': 'Kami akan mengirim link reset jika email terdaftar.', 'auth.send_reset': 'Kirim link reset', 'auth.sending_link': 'Mengirim link…', 'auth.back_login': 'Kembali ke login', 'auth.new_password_title': 'Buat kata sandi baru', 'auth.checking_link': 'Memverifikasi link reset…', 'auth.save_password': 'Simpan kata sandi baru', 'auth.saving_password': 'Menyimpan kata sandi…', 'auth.request_new_link': 'Minta link reset baru', 'auth.password_mismatch': 'Konfirmasi kata sandi tidak cocok.',
    'auth.login_title': 'Masuk ke Vue Rails',
    'dashboard.subtitle': 'Ringkasan workspace Vue Rails Anda',
    'api_docs.subtitle': 'Kontrak OpenAPI interaktif untuk endpoint Vue Rails.',
  },
  en: {
    'security.additional_verification': 'Additional security verification', 'security.step_up_hint': 'Confirm your identity before continuing this sensitive action.', 'security.totp_or_email_hint': 'Use an authenticator-app code or the code sent by email.', 'security.totp_title': 'Authenticator app', 'security.totp_hint': 'Use TOTP codes even when email is unavailable.', 'security.totp_setup_hint': 'Add this secret to your authenticator app, then enter its 6-digit code.', 'security.totp_enabled': 'Authenticator app enabled successfully.', 'security.totp_disabled': 'Authenticator app disabled successfully.', 'security.email_revert_title': 'Revert email change', 'security.email_revert_hint': 'We are restoring the previous email address and ending every session.', 'security.email_reverted': 'The email address was restored. Please sign in again.',
    'nav.account_security': 'Account security',
    'security.title': 'Account security', 'security.subtitle': 'Manage credentials and review your account login activity.', 'security.current_password': 'Current password', 'security.change_password': 'Change password', 'security.changing_password': 'Changing…', 'security.password_changed': 'Password changed and other sessions were revoked.', 'security.change_email': 'Change email', 'security.new_email': 'New email', 'security.send_email_code': 'Send verification code', 'security.sending_code': 'Sending code…', 'security.email_code_sent': 'A verification code was sent to {email}.', 'security.verify_email': 'Verify new email', 'security.email_changed': 'Email changed successfully.', 'security.login_history': 'Login history', 'security.event': 'Activity', 'security.time': 'Time', 'security.empty_history': 'No security history yet.', 'security.recovery_title': 'Recovery codes', 'security.recovery_hint': 'Confirm your password and OTP before regenerating recovery codes.', 'security.request_recovery': 'Send OTP', 'security.regenerate': 'Regenerate codes', 'security.recovery_generated': 'New recovery codes were generated.', 'security.recovery_once': 'Save these now. They are only shown once.', 'security.passkeys': 'Passkeys', 'security.passkey_hint': 'Use biometrics or a security key in a supported browser.', 'security.passkey_name': 'Device name', 'security.add_passkey': 'Add passkey', 'security.adding_passkey': 'Adding…', 'security.passkey_added': 'Passkey added successfully.', 'security.passkey_removed': 'Passkey removed successfully.', 'security.remove_passkey': 'Remove passkey {name}', 'security.confirm_remove_passkey': 'Passkey {name} will be removed.', 'security.passkeys_disabled': 'Passkeys are not configured on the server.', 'security.passkeys_unsupported': 'This browser does not support modern passkeys.', 'security.never_used': 'Never used', 'security.use_passkey': 'Sign in with passkey', 'security.using_passkey': 'Verifying passkey…',
    'permission.account_security.view.name': 'View account security', 'permission.account_security.view.description': 'View your own security settings and login history.', 'permission.account_security.update.name': 'Update account security', 'permission.account_security.update.description': 'Change your own password, email, recovery codes, and passkeys.',
    'profile.title': 'Profile', 'profile.subtitle': 'Manage your personal information and account security access.', 'profile.menu': 'Profile', 'profile.avatar_alt': 'Profile photo', 'profile.account_info': 'Account information', 'profile.member_since': 'Member since', 'profile.verified': 'Email verified', 'profile.unverified': 'Email not verified', 'profile.security_link_hint': 'Password, email, recovery codes, and passkeys.', 'profile.sessions_link_hint': 'Review devices and active login sessions.', 'profile.avatar_title': 'Profile photo', 'profile.avatar_hint': 'JPEG, PNG, or WebP up to 5 MB.', 'profile.avatar_file': 'Choose image', 'profile.upload': 'Upload', 'profile.uploading': 'Uploading…', 'profile.remove': 'Remove photo', 'profile.avatar_updated': 'Profile photo was updated.', 'profile.avatar_removed': 'Profile photo was removed.',
    'permission.profile.view.name': 'View profile', 'permission.profile.view.description': 'View your own account profile.', 'permission.profile.update.name': 'Update profile', 'permission.profile.update.description': 'Change your own profile photo and profile information.',
    'profile.sections': 'Profile sections', 'profile.account_menu': 'Account menu', 'profile.tab_overview': 'Overview', 'profile.tab_security': 'Account security', 'profile.tab_devices': 'Active devices',
    'profile.personal_information': 'Personal information', 'profile.personal_hint': 'Update the name and phone number connected to your account.', 'profile.edit_personal': 'Edit personal information', 'profile.first_name': 'First name', 'profile.last_name': 'Last name', 'profile.phone': 'Phone number', 'profile.personal_updated': 'Personal information was updated.', 'profile.change_photo': 'Change profile photo', 'profile.avatar_conversion_hint': 'Every photo is converted to AVIF at no more than 50 KB.', 'profile.password_hint': 'Securely update your account password.', 'profile.email_hint': 'Change your email with verification.', 'profile.history_hint': 'Review recent security and login activity.',
    'auth.otp_or_recovery': 'Enter a 6-digit OTP or a 10-character recovery code.', 'auth.captcha_hint': 'Complete the security check to continue signing in.', 'auth.session_expired': 'Your session has expired. Please sign in again.',
    'sessions.recovery_title': 'Recovery codes', 'sessions.recovery_hint': 'Create one-time codes for signing in when email OTP is unavailable.', 'sessions.recovery_generate': 'Generate new codes', 'sessions.recovery_generating': 'Generating…', 'sessions.recovery_generated': 'New recovery codes were generated.', 'sessions.recovery_once': 'Save these now. They are shown once and each code can only be used one time.',
    'admin.open_menu': 'Open menu',
    'admin.notifications': 'Notifications', 'admin.no_notifications': 'There are no new notifications.',
    'validation.email_same': 'The new email must differ from the current email.',
    'validation.required': 'This field is required.', 'validation.too_long': 'This value is too long.', 'validation.email': 'Enter a valid email address.', 'validation.password_min': 'Password must be at least 12 characters.', 'validation.password_mismatch': 'Password confirmation does not match.', 'validation.password_same': 'The new password must differ from the current password.', 'validation.otp': 'Enter a valid 6-digit OTP.', 'validation.otp_or_recovery': 'Enter a 6-digit OTP or 10-character recovery code.', 'validation.phone': 'Use only numbers, spaces, +, parentheses, periods, or hyphens.', 'validation.role_key': 'The key may only contain lowercase letters, numbers, and underscores.', 'validation.fix_fields': 'Check the highlighted fields.',
    'nav.home': 'Home', 'nav.admin': 'Admin', 'nav.language': 'Language',
    'nav.dashboard': 'Dashboard', 'nav.user_management': 'User Management', 'nav.users': 'Users', 'nav.roles': 'Roles', 'nav.sessions': 'Active devices', 'nav.audit_logs': 'Audit logs', 'nav.jobs': 'Job queue', 'nav.api_docs': 'API documentation', 'nav.security_approvals': 'Security approvals',
    'common.close': 'Close', 'common.done': 'Done', 'common.continue': 'Continue', 'common.verify': 'Verify',
    'common.edit': 'Edit', 'common.view': 'View', 'common.cancel': 'Cancel',
    'common.loading_data': 'Loading data…',
    'api.non_json_response': 'The server returned a non-JSON response (HTTP {status}).',
    'table.show': 'Show', 'table.entries': 'entries', 'table.search': 'Search…', 'table.empty': 'No data available.', 'table.loading': 'Loading data…', 'table.showing': 'Showing {from}–{to} of {total} entries', 'table.previous': 'Previous', 'table.next': 'Next',
    'common.loading_page': 'Loading page…', 'common.processing': 'Processing…', 'common.back': 'Back', 'common.retry': 'Try again', 'common.back_home': 'Back to home', 'common.just_now': 'Just now', 'common.close_notification': 'Close notification', 'common.save': 'Save', 'common.saving': 'Saving…', 'common.delete': 'Delete', 'common.deleting': 'Deleting…', 'common.action': 'Action', 'common.status': 'Status', 'common.system': 'System', 'common.view_only': 'View only',
    'auth.login_required': 'Please sign in first to access the admin page.', 'auth.otp_sent': 'An OTP code was sent to {email}.', 'auth.unverified': 'Your account is not verified. A verification code was sent to {email}.', 'auth.otp_resent': 'A new OTP code was sent to {email}.', 'auth.no_permission': 'This account does not have permission to access the admin panel.', 'auth.password_updated': 'Password updated successfully. Please sign in.',
    'auth.admin_access': 'Admin access', 'auth.login_title': 'Sign in to Vue Rails', 'auth.verify_title': 'Verify OTP', 'auth.login_hint': 'Use your administrator account.', 'auth.otp_hint': 'Enter the 6-digit code sent to {email}.', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.confirm_password': 'Confirm password', 'auth.new_password': 'New password', 'auth.otp': 'OTP code', 'auth.forgot': 'Forgot password?', 'auth.login': 'Login', 'auth.logging_in': 'Signing in…', 'auth.verify': 'Verify', 'auth.verifying': 'Verifying…', 'auth.no_account': 'No account yet?', 'auth.register_member': 'Register as a member', 'auth.resend': 'Resend OTP', 'auth.resending': 'Sending…', 'auth.resend_countdown': 'Resend ({seconds}s)', 'auth.password_min': 'At least 12 characters.',
    'toast.success': 'Success', 'toast.error': 'Error', 'toast.warning': 'Warning', 'toast.info': 'Information', 'toast.confirm': 'Confirm action', 'toast.cancel': 'Cancel', 'toast.continue': 'Continue',
    'admin.console': 'Admin console', 'admin.menu': 'Menu', 'admin.operational': 'All systems operational', 'admin.collapse_sidebar': 'Collapse sidebar', 'admin.expand_sidebar': 'Expand sidebar', 'admin.search': 'Search or type command...', 'admin.administrator': 'Administrator', 'admin.sign_out': 'Sign out', 'admin.signing_out': 'Signing out…',
    'users.title': 'User management', 'users.subtitle': 'Manage account roles and access.', 'users.search': 'Search email…', 'users.search_button': 'Search', 'users.searching': 'Searching…', 'users.role': 'Role', 'users.verified': 'Verified', 'users.you': 'You', 'users.active': 'Active', 'users.inactive': 'Inactive', 'users.email_verified': 'Email verified', 'users.email_unverified': 'Email not verified', 'users.empty': 'No users found.', 'users.updated': '{email} was updated successfully.',
    'users.edit_title': 'Edit user', 'users.edit_user': 'Edit user {email}', 'users.account_status': 'Account status', 'users.account_status_hint': 'Inactive users cannot sign in to the application.',
    'roles.title': 'Role management', 'roles.subtitle': 'Create roles and use them in user management.', 'roles.name': 'Role name', 'roles.key': 'Key', 'roles.description': 'Description', 'roles.permissions': 'Permissions', 'roles.key_help': 'Lowercase letters, numbers, and underscores.', 'roles.add': 'Add role', 'roles.adding': 'Adding…', 'roles.created': 'The role was created successfully.', 'roles.updated': '{name} was updated successfully.', 'roles.deleted': '{name} was deleted successfully.', 'roles.confirm_delete': 'Role {name} will be permanently deleted.', 'roles.users': 'Users', 'roles.empty': 'No roles yet.',
    'audit.title': 'Audit logs', 'audit.subtitle': 'The latest 100 security-relevant activities.', 'audit.action': 'Action', 'audit.actor': 'Actor', 'audit.target': 'Target', 'audit.time': 'Time', 'audit.empty': 'No activity yet.',
    'sessions.last_seen': 'Last activity', 'sessions.expires_at': 'Expires',
    'sessions.title': 'Active devices', 'sessions.subtitle': 'Review and revoke login sessions for your account.', 'sessions.device': 'Device / browser', 'sessions.login_time': 'Login time', 'sessions.current': 'Current', 'sessions.empty': 'No active sessions.', 'sessions.unknown_device': 'Unknown device', 'sessions.revoke': 'Revoke', 'sessions.revoking': 'Revoking…', 'sessions.revoked': 'The session was revoked.', 'sessions.revoke_others': 'Revoke other sessions', 'sessions.others_revoked': 'All other sessions were revoked.', 'sessions.confirm_revoke': 'The session on this device will be revoked.', 'sessions.confirm_revoke_others': 'Every session except the device currently in use will be revoked.', 'sessions.revoke_device': 'Revoke session for {device}', 'sessions.use_sign_out': 'Use the Sign out button',
    'home.title': 'Modern travel planning stack', 'home.subtitle': 'Vue handles the interface, Rails provides the REST API, and PostgreSQL stores the data.', 'home.connecting': 'Connecting to the Rails API…', 'home.connected': 'API connected', 'home.disconnected': 'API not connected',
    'dashboard.title': 'Dashboard', 'dashboard.subtitle': 'Overview of your Vue Rails workspace', 'dashboard.load_failed': 'The dashboard could not be loaded. Please try again.', 'dashboard.total_users': 'Total users', 'dashboard.active_sessions': 'Active sessions', 'dashboard.live': 'Live', 'dashboard.database': 'Database', 'dashboard.connected': 'Connected', 'dashboard.authorization': 'Authorization', 'dashboard.protected': 'Protected', 'dashboard.overview': 'Workspace overview', 'dashboard.system_activity': 'System activity for this application', 'dashboard.last_days': 'Last 7 days', 'dashboard.quick_status': 'Quick status', 'dashboard.backend_services': 'Backend services', 'dashboard.operational': 'Operational', 'dashboard.recent_activity': 'Recent admin activity', 'dashboard.auth_events': 'Authentication and system events', 'dashboard.event': 'Event', 'dashboard.account': 'Account', 'dashboard.session_authenticated': 'Admin session authenticated', 'dashboard.success': 'Success',
    'roles.name_placeholder': 'Example: Editor', 'roles.more': 'More (+{count})', 'roles.permission_modal_title': 'Select permissions', 'roles.permission_modal_hint': 'Choose the pages and actions this role is allowed to use.',
    'roles.edit_title': 'Edit role', 'roles.edit_hint': 'Update the role with key {key}.', 'roles.edit_role': 'Edit role {name}', 'roles.delete_role': 'Delete role {name}', 'roles.description_placeholder': 'Describe this role’s responsibilities and access scope.', 'roles.no_description': 'No description yet.', 'roles.permission_count': '{count} permissions',
    'permission.dashboard.view.name': 'View dashboard', 'permission.dashboard.view.description': 'View the admin dashboard.',
    'permission.users.view.name': 'View users', 'permission.users.view.description': 'View the user list and details.',
    'permission.users.update.name': 'Update users', 'permission.users.update.description': 'Change user roles and status.',
    'permission.roles.view.name': 'View roles', 'permission.roles.view.description': 'View roles and permissions.',
    'permission.roles.create.name': 'Create roles', 'permission.roles.create.description': 'Create new roles and assign their initial permissions.',
    'permission.roles.update.name': 'Update roles', 'permission.roles.update.description': 'Change role names, descriptions, and permissions.',
    'permission.roles.delete.name': 'Delete roles', 'permission.roles.delete.description': 'Delete unused custom roles.',
    'permission.audit_logs.view.name': 'View audit logs', 'permission.audit_logs.view.description': 'View the security activity history.',
    'permission.sessions.view.name': 'View devices', 'permission.sessions.view.description': 'View your own devices and login sessions.', 'permission.sessions.delete.name': 'Revoke sessions', 'permission.sessions.delete.description': 'Revoke your own login sessions.',
    'permission.jobs.view.name': 'View job queue', 'permission.jobs.view.description': 'View queue status and failed jobs.', 'permission.jobs.update.name': 'Manage failed jobs', 'permission.jobs.update.description': 'Retry or discard failed jobs.', 'permission.api_docs.view.name': 'View API documentation', 'permission.api_docs.view.description': 'Open the interactive OpenAPI documentation.',
    'jobs.title': 'Job queue', 'jobs.subtitle': 'Monitor Solid Queue and handle failed jobs.', 'jobs.ready': 'Ready', 'jobs.scheduled': 'Scheduled', 'jobs.claimed': 'Processing', 'jobs.failed': 'Failed', 'jobs.job': 'Job', 'jobs.error': 'Error', 'jobs.failed_at': 'Failed at', 'jobs.empty': 'No failed jobs.', 'jobs.retry': 'Retry', 'jobs.discard': 'Discard', 'jobs.retryed': 'The job was queued again.', 'jobs.discarded': 'The failed job was discarded.', 'jobs.confirm_retry': 'This failed job will be retried.', 'jobs.confirm_discard': 'This failed job will be permanently discarded.', 'jobs.retry_job': 'Retry job {id}', 'jobs.discard_job': 'Discard job {id}',
    'api_docs.title': 'API documentation', 'api_docs.subtitle': 'Interactive OpenAPI contract for Vue Rails endpoints.',
    'approvals.title': 'Security approvals', 'approvals.subtitle': 'Review access changes requested by another administrator.', 'approvals.action': 'Change', 'approvals.requester': 'Requester', 'approvals.requested_at': 'Requested', 'approvals.expires_at': 'Expires', 'approvals.review': 'Review and approve', 'approvals.approved': 'The change was approved.', 'approvals.empty': 'No approvals are waiting.',
    'permission.security_approvals.view.name': 'View security approvals', 'permission.security_approvals.view.description': 'View admin changes awaiting approval.', 'permission.security_approvals.update.name': 'Approve security changes', 'permission.security_approvals.update.description': 'Approve sensitive changes requested by another administrator.',
    'error.403_title': 'Access denied', 'error.403_message': 'You do not have permission to open this page.', 'error.404_title': 'Page not found', 'error.404_message': 'The page you are looking for is unavailable or has moved.', 'error.500_title': 'Something went wrong', 'error.500_message': 'The application encountered an unexpected problem.',
    'auth.registration': 'Member registration', 'auth.register_title': 'Create account', 'auth.verify_email': 'Verify email', 'auth.register_hint': 'Register as a new member.', 'auth.register': 'Register', 'auth.registering': 'Registering…', 'auth.verify_and_login': 'Verify and sign in', 'auth.have_account': 'Already have an account?', 'auth.recovery': 'Account recovery', 'auth.forgot_title': 'Forgot password', 'auth.forgot_hint': 'We will send a reset link if the email is registered.', 'auth.send_reset': 'Send reset link', 'auth.sending_link': 'Sending link…', 'auth.back_login': 'Back to login', 'auth.new_password_title': 'Create a new password', 'auth.checking_link': 'Verifying reset link…', 'auth.save_password': 'Save new password', 'auth.saving_password': 'Saving password…', 'auth.request_new_link': 'Request a new reset link', 'auth.password_mismatch': 'Password confirmation does not match.',
    'auth.login_title': 'Sign in to Vue Rails',
    'dashboard.subtitle': 'Overview of your Vue Rails workspace',
    'api_docs.subtitle': 'Interactive OpenAPI contract for Vue Rails endpoints.',
  },
}

const savedLocale = localStorage.getItem('locale')
export const locale = ref(savedLocale === 'en' ? 'en' : 'id')

export function setLocale(value, showLoading = true) {
  const nextLocale = value === 'en' ? 'en' : 'id'
  if (nextLocale === locale.value && document.documentElement.lang === nextLocale) return
  if (showLoading) startNavigationLoading()
  locale.value = nextLocale
  localStorage.setItem('locale', locale.value)
  document.documentElement.lang = locale.value
  if (showLoading) finishNavigationLoading()
}

export function t(key, params = {}) {
  let value = messages[locale.value]?.[key] || messages.id[key] || key
  Object.entries(params).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, replacement) })
  return value
}

setLocale(locale.value, false)
