import { ref } from 'vue'

const messages = {
  id: {
    'nav.home': 'Beranda', 'nav.admin': 'Admin', 'nav.language': 'Bahasa',
    'nav.dashboard': 'Dasbor', 'nav.user_management': 'Manajemen Pengguna', 'nav.users': 'Pengguna', 'nav.roles': 'Role', 'nav.audit_logs': 'Log audit',
    'common.loading_page': 'Memuat halaman…', 'common.processing': 'Memproses…', 'common.back': 'Kembali', 'common.retry': 'Coba lagi', 'common.back_home': 'Kembali ke beranda', 'common.just_now': 'Baru saja', 'common.close_notification': 'Tutup notifikasi', 'common.save': 'Simpan', 'common.saving': 'Menyimpan…', 'common.delete': 'Hapus', 'common.deleting': 'Menghapus…', 'common.action': 'Aksi', 'common.status': 'Status', 'common.system': 'Sistem', 'common.view_only': 'Hanya lihat',
    'auth.login_required': 'Silakan login terlebih dahulu untuk mengakses halaman admin.', 'auth.otp_sent': 'Kode OTP telah dikirim ke {email}.', 'auth.unverified': 'Akun belum terverifikasi. Kode verifikasi telah dikirim ke {email}.', 'auth.otp_resent': 'Kode OTP baru telah dikirim ke {email}.', 'auth.no_permission': 'Akun ini tidak memiliki izin untuk mengakses panel admin.', 'auth.password_updated': 'Kata sandi berhasil diperbarui. Silakan login.',
    'auth.admin_access': 'Akses admin', 'auth.login_title': 'Masuk ke Tourplan', 'auth.verify_title': 'Verifikasi OTP', 'auth.login_hint': 'Gunakan akun administrator Anda.', 'auth.otp_hint': 'Masukkan kode 6 digit yang dikirim ke {email}.', 'auth.email': 'Email', 'auth.password': 'Kata sandi', 'auth.confirm_password': 'Konfirmasi kata sandi', 'auth.new_password': 'Kata sandi baru', 'auth.otp': 'Kode OTP', 'auth.forgot': 'Lupa kata sandi?', 'auth.login': 'Login', 'auth.logging_in': 'Masuk…', 'auth.verify': 'Verifikasi', 'auth.verifying': 'Memverifikasi…', 'auth.no_account': 'Belum punya akun?', 'auth.register_member': 'Daftar sebagai member', 'auth.resend': 'Kirim ulang OTP', 'auth.resending': 'Mengirim…', 'auth.resend_countdown': 'Kirim ulang ({seconds}s)', 'auth.password_min': 'Minimal 12 karakter.',
    'toast.success': 'Berhasil', 'toast.error': 'Terjadi kesalahan', 'toast.warning': 'Perhatian', 'toast.info': 'Informasi', 'toast.confirm': 'Konfirmasi tindakan', 'toast.cancel': 'Batal', 'toast.continue': 'Lanjutkan',
    'admin.console': 'Konsol admin', 'admin.menu': 'Menu', 'admin.operational': 'Semua sistem beroperasi', 'admin.collapse_sidebar': 'Kecilkan sidebar', 'admin.expand_sidebar': 'Lebarkan sidebar', 'admin.search': 'Cari atau ketik perintah...', 'admin.administrator': 'Administrator', 'admin.sign_out': 'Keluar', 'admin.signing_out': 'Keluar…',
    'users.title': 'Manajemen pengguna', 'users.subtitle': 'Kelola role dan akses akun.', 'users.search': 'Cari email…', 'users.search_button': 'Cari', 'users.searching': 'Mencari…', 'users.role': 'Role', 'users.verified': 'Terverifikasi', 'users.you': 'Anda', 'users.active': 'Aktif', 'users.inactive': 'Nonaktif', 'users.email_verified': 'Email terverifikasi', 'users.email_unverified': 'Email belum terverifikasi', 'users.empty': 'Pengguna tidak ditemukan.', 'users.updated': '{email} berhasil diperbarui.',
    'roles.title': 'Manajemen role', 'roles.subtitle': 'Buat role dan gunakan pada manajemen pengguna.', 'roles.name': 'Nama role', 'roles.key': 'Key', 'roles.description': 'Deskripsi', 'roles.permissions': 'Izin', 'roles.key_help': 'Huruf kecil, angka, dan underscore.', 'roles.add': 'Tambah role', 'roles.adding': 'Menambahkan…', 'roles.created': 'Role baru berhasil dibuat.', 'roles.updated': '{name} berhasil diperbarui.', 'roles.deleted': '{name} berhasil dihapus.', 'roles.confirm_delete': 'Role {name} akan dihapus permanen.', 'roles.users': 'Pengguna', 'roles.empty': 'Belum ada role.',
    'audit.title': 'Log audit', 'audit.subtitle': '100 aktivitas terbaru yang penting bagi keamanan.', 'audit.action': 'Aksi', 'audit.actor': 'Pelaku', 'audit.target': 'Target', 'audit.time': 'Waktu', 'audit.empty': 'Belum ada aktivitas.',
    'home.title': 'Stack modern untuk perencanaan perjalanan', 'home.subtitle': 'Vue menangani antarmuka, Rails menyediakan REST API, dan PostgreSQL menyimpan data.', 'home.connecting': 'Menghubungkan ke Rails API…', 'home.connected': 'API terhubung', 'home.disconnected': 'API belum terhubung',
    'error.403_title': 'Akses ditolak', 'error.403_message': 'Anda tidak memiliki izin untuk membuka halaman ini.', 'error.404_title': 'Halaman tidak ditemukan', 'error.404_message': 'Halaman yang Anda cari tidak tersedia atau telah dipindahkan.', 'error.500_title': 'Terjadi kesalahan', 'error.500_message': 'Aplikasi mengalami masalah yang tidak terduga.',
    'auth.registration': 'Pendaftaran member', 'auth.register_title': 'Buat akun', 'auth.verify_email': 'Verifikasi email', 'auth.register_hint': 'Daftar sebagai member baru.', 'auth.register': 'Daftar', 'auth.registering': 'Mendaftarkan…', 'auth.verify_and_login': 'Verifikasi dan masuk', 'auth.have_account': 'Sudah punya akun?', 'auth.recovery': 'Pemulihan akun', 'auth.forgot_title': 'Lupa kata sandi', 'auth.forgot_hint': 'Kami akan mengirim link reset jika email terdaftar.', 'auth.send_reset': 'Kirim link reset', 'auth.sending_link': 'Mengirim link…', 'auth.back_login': 'Kembali ke login', 'auth.new_password_title': 'Buat kata sandi baru', 'auth.checking_link': 'Memverifikasi link reset…', 'auth.save_password': 'Simpan kata sandi baru', 'auth.saving_password': 'Menyimpan kata sandi…', 'auth.request_new_link': 'Minta link reset baru', 'auth.password_mismatch': 'Konfirmasi kata sandi tidak cocok.',
  },
  en: {
    'nav.home': 'Home', 'nav.admin': 'Admin', 'nav.language': 'Language',
    'nav.dashboard': 'Dashboard', 'nav.user_management': 'User Management', 'nav.users': 'Users', 'nav.roles': 'Roles', 'nav.audit_logs': 'Audit logs',
    'common.loading_page': 'Loading page…', 'common.processing': 'Processing…', 'common.back': 'Back', 'common.retry': 'Try again', 'common.back_home': 'Back to home', 'common.just_now': 'Just now', 'common.close_notification': 'Close notification', 'common.save': 'Save', 'common.saving': 'Saving…', 'common.delete': 'Delete', 'common.deleting': 'Deleting…', 'common.action': 'Action', 'common.status': 'Status', 'common.system': 'System', 'common.view_only': 'View only',
    'auth.login_required': 'Please sign in first to access the admin page.', 'auth.otp_sent': 'An OTP code was sent to {email}.', 'auth.unverified': 'Your account is not verified. A verification code was sent to {email}.', 'auth.otp_resent': 'A new OTP code was sent to {email}.', 'auth.no_permission': 'This account does not have permission to access the admin panel.', 'auth.password_updated': 'Password updated successfully. Please sign in.',
    'auth.admin_access': 'Admin access', 'auth.login_title': 'Sign in to Tourplan', 'auth.verify_title': 'Verify OTP', 'auth.login_hint': 'Use your administrator account.', 'auth.otp_hint': 'Enter the 6-digit code sent to {email}.', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.confirm_password': 'Confirm password', 'auth.new_password': 'New password', 'auth.otp': 'OTP code', 'auth.forgot': 'Forgot password?', 'auth.login': 'Login', 'auth.logging_in': 'Signing in…', 'auth.verify': 'Verify', 'auth.verifying': 'Verifying…', 'auth.no_account': 'No account yet?', 'auth.register_member': 'Register as a member', 'auth.resend': 'Resend OTP', 'auth.resending': 'Sending…', 'auth.resend_countdown': 'Resend ({seconds}s)', 'auth.password_min': 'At least 12 characters.',
    'toast.success': 'Success', 'toast.error': 'Error', 'toast.warning': 'Warning', 'toast.info': 'Information', 'toast.confirm': 'Confirm action', 'toast.cancel': 'Cancel', 'toast.continue': 'Continue',
    'admin.console': 'Admin console', 'admin.menu': 'Menu', 'admin.operational': 'All systems operational', 'admin.collapse_sidebar': 'Collapse sidebar', 'admin.expand_sidebar': 'Expand sidebar', 'admin.search': 'Search or type command...', 'admin.administrator': 'Administrator', 'admin.sign_out': 'Sign out', 'admin.signing_out': 'Signing out…',
    'users.title': 'User management', 'users.subtitle': 'Manage account roles and access.', 'users.search': 'Search email…', 'users.search_button': 'Search', 'users.searching': 'Searching…', 'users.role': 'Role', 'users.verified': 'Verified', 'users.you': 'You', 'users.active': 'Active', 'users.inactive': 'Inactive', 'users.email_verified': 'Email verified', 'users.email_unverified': 'Email not verified', 'users.empty': 'No users found.', 'users.updated': '{email} was updated successfully.',
    'roles.title': 'Role management', 'roles.subtitle': 'Create roles and use them in user management.', 'roles.name': 'Role name', 'roles.key': 'Key', 'roles.description': 'Description', 'roles.permissions': 'Permissions', 'roles.key_help': 'Lowercase letters, numbers, and underscores.', 'roles.add': 'Add role', 'roles.adding': 'Adding…', 'roles.created': 'The role was created successfully.', 'roles.updated': '{name} was updated successfully.', 'roles.deleted': '{name} was deleted successfully.', 'roles.confirm_delete': 'Role {name} will be permanently deleted.', 'roles.users': 'Users', 'roles.empty': 'No roles yet.',
    'audit.title': 'Audit logs', 'audit.subtitle': 'The latest 100 security-relevant activities.', 'audit.action': 'Action', 'audit.actor': 'Actor', 'audit.target': 'Target', 'audit.time': 'Time', 'audit.empty': 'No activity yet.',
    'home.title': 'Modern travel planning stack', 'home.subtitle': 'Vue handles the interface, Rails provides the REST API, and PostgreSQL stores the data.', 'home.connecting': 'Connecting to the Rails API…', 'home.connected': 'API connected', 'home.disconnected': 'API not connected',
    'error.403_title': 'Access denied', 'error.403_message': 'You do not have permission to open this page.', 'error.404_title': 'Page not found', 'error.404_message': 'The page you are looking for is unavailable or has moved.', 'error.500_title': 'Something went wrong', 'error.500_message': 'The application encountered an unexpected problem.',
    'auth.registration': 'Member registration', 'auth.register_title': 'Create account', 'auth.verify_email': 'Verify email', 'auth.register_hint': 'Register as a new member.', 'auth.register': 'Register', 'auth.registering': 'Registering…', 'auth.verify_and_login': 'Verify and sign in', 'auth.have_account': 'Already have an account?', 'auth.recovery': 'Account recovery', 'auth.forgot_title': 'Forgot password', 'auth.forgot_hint': 'We will send a reset link if the email is registered.', 'auth.send_reset': 'Send reset link', 'auth.sending_link': 'Sending link…', 'auth.back_login': 'Back to login', 'auth.new_password_title': 'Create a new password', 'auth.checking_link': 'Verifying reset link…', 'auth.save_password': 'Save new password', 'auth.saving_password': 'Saving password…', 'auth.request_new_link': 'Request a new reset link', 'auth.password_mismatch': 'Password confirmation does not match.',
  },
}

const savedLocale = localStorage.getItem('locale')
export const locale = ref(savedLocale === 'en' ? 'en' : 'id')

export function setLocale(value) {
  locale.value = value === 'en' ? 'en' : 'id'
  localStorage.setItem('locale', locale.value)
  document.documentElement.lang = locale.value
}

export function t(key, params = {}) {
  let value = messages[locale.value]?.[key] || messages.id[key] || key
  Object.entries(params).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, replacement) })
  return value
}

setLocale(locale.value)
